-- team table create
CREATE TABLE TEAM_TB (
  "ID" NUMBER NOT NULL ENABLE, 
  "NAME" VARCHAR2(50 BYTE), 
  "REGION" VARCHAR2(50 BYTE), 
  "MANAGER" VARCHAR2(50 BYTE), 
  "STADIUM" VARCHAR2(50 BYTE), 
  "LOGO" VARCHAR2(200 BYTE), 
  CONSTRAINT "TEAM_TB_PK" PRIMARY KEY ("ID")
);

COMMENT ON COLUMN "TEAM_TB"."ID" IS '아이디';
COMMENT ON COLUMN "TEAM_TB"."NAME" IS '팀명';
COMMENT ON COLUMN "TEAM_TB"."REGION" IS '연고지';
COMMENT ON COLUMN "TEAM_TB"."MANAGER" IS '감독';
COMMENT ON COLUMN "TEAM_TB"."STADIUM" IS '홈구장';
COMMENT ON COLUMN "TEAM_TB"."LOGO" IS '이미지경로';

-- player table create
CREATE TABLE PLAYER_TB (
  "ID" NUMBER NOT NULL ENABLE, 
  "TEAMID" NUMBER, 
  "NAME" VARCHAR2(50 BYTE), 
  "BACKNUMBER" NUMBER(3,0), 
  "POSITION" VARCHAR2(50 BYTE), 
  "HITTING" CHAR(1 BYTE), 
  "THROW" CHAR(1 BYTE)
);

COMMENT ON COLUMN "PLAYER_TB"."ID" IS '아이디';
COMMENT ON COLUMN "PLAYER_TB"."TEAMID" IS '소속팀아이디';
COMMENT ON COLUMN "PLAYER_TB"."NAME" IS '이름';
COMMENT ON COLUMN "PLAYER_TB"."BACKNUMBER" IS '등번호';
COMMENT ON COLUMN "PLAYER_TB"."POSITION" IS '포지션';
COMMENT ON COLUMN "PLAYER_TB"."HITTING" IS '타격';
COMMENT ON COLUMN "PLAYER_TB"."THROW" IS '송구';


-- team table sequence create
CREATE SEQUENCE  "TEAM_TB_SEQ" INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

-- player table sequence create
CREATE SEQUENCE  "PLAYER_TB_SEQ" INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
   